config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :roles, except: [:show]
    resources :permissions, except: [:show]
    resources :permission_sets
    resource :default_admin_dashboard, only: :show
  end
end

app/models/spree/permission.rb
module Spree
  class Permission < ActiveRecord::Base
    include Permissions

    default_scope { order(:priority) }

    # DEPRECATED: Use permission sets instead only here for aiding migration for existing users
    has_and_belongs_to_many :legacy_roles, join_table: 'spree_roles_permissions', class_name: 'Spree::Role'

    has_many :permissions_permission_sets, dependent: :destroy
    has_many :permission_sets, through: :permissions_permission_sets

    validates :title, presence: true, uniqueness: true

    scope :visible, lambda { where(visible: true) }

    def ability(current_ability, user)
      send(title, current_ability, user)
    end

    def name
      title.gsub('-', '_').humanize
    end
  end
end

app/controllers/spree/admin/permissions_controller.rb
module Spree
  module Admin
    class PermissionsController < ResourceController
    end
  end
end

app/views/spree/admin/permissions/_fields.html.erb
<div data-hook="admin_permission_form" class="align-center row">
  <div class="alpha <%= request.xhr? || content_for?(:sidebar) ? 'twelve' : 'eight' %> columns">
    <%= f.field_container(:title) do %>
      <%= f.label(:title, Spree.t(:title)) %> <span class="required">*</span><br />
      <%= f.text_field(:title, { class: 'fullwidth' }) %>
    <% end %>
  </div>
</div>

app/views/spree/admin/permissions/_form.html.erb
<div class="panel-group" id="permission-writing-guide">
  <div class="panel panel-info">
    <div class="panel-heading" role="button" data-toggle="collapse" data-target="#permission-list-guide">
      <h3 class="panel-title">Pattern of the permissions <i class="icon icon-circle-arrow-right"></i></h3>
    </div>

    <ul class="list-group collapse" id="permission-list-guide">
      <li class="list-group-item">Can/cannot - specifies whether the user with that permission can do or cannot do that task.</li>
      <li class="list-group-item">Action - specifies the action which can be done by that model or subject like update, index, create etc. There is a special action called manage which matches every action.</li>
      <li class="list-group-item">Subject - specified the model like products, users etc. of which the permission is given. There is an special subject called all which matches every subject.</li>
      <li class="list-group-item">Attributes - specifies the attributes for which the permission is specified. Read-only actions shouldn't require this like index, read etc. But it is more secure if we specify them in other actions like create or update.</li>
    </ul>
  </div>

  <div class="panel panel-info">
    <div class="panel-heading" role="button" data-toggle="collapse" data-target="#permission-example">
      <h3 class="panel-title">Some examples of permissions <i class="icon icon-circle-arrow-right"></i></h3>
    </div>

    <ul class="list-group collapse" id="permission-example">
      <li class="list-group-item">can-manage-spree/product - can perform every action on Spree::Product but not on any other model or subject.</li>
      <li class="list-group-item">can-update-all - can update all models or subjects.</li>
      <li class="list-group-item">can-update-spree/product - can update only products, and not users, orders and other things.</li>
      <li class="list-group-item">can-update-spree/product-price - can update only price of products.</li>
      <li class="list-group-item">can-manage-all - can perform every action on all models.</li>
    </ul>
  </div>
</div>

<div data-hook="admin_permission_form_fields">
  <div data-hook="permission_title" class="form-group">
    <%= f.label :title, Spree.t(:permission_title) %> <span class="required">*</span>
    <%= f.text_field :title, class: 'form-control' %>
    <a href="#permission-writing-guide" class="help-block">help</a>
  </div>
  <div data-hook="permission_description" class="form-group">
    <%= f.label :description, Spree.t(:permission_description) %>
    <%= f.text_field :description, class: 'form-control', placeholder: 'This allows the permitted user to..' %>
  </div>
  <div data-hook="permission_priority" class="form-group">
    <%= f.label :priority, Spree.t(:permission_priority) %> <span class="required">*</span>
    <%= f.number_field :priority, in: 0..9, step: 1, class: 'form-control' %>
    <p class="help-block"><%= Spree.t(:permission_priority_help) %></p>
  </div>
  <div data-hook="permission_visible" class="checkbox">
    <label>
      <%= f.check_box :visible, value: true %><%= Spree.t(:permission_visible) %>
      <p class="help-block"><%= Spree.t(:permission_visible_help) %></p>
    </label>
  </div>

  <div data-hook="additional_permission_fields"></div>
</div>

app/views/spree/admin/permissions/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:permissions), admin_permissions_path %> /
  <%= Spree.t(:editing_resource, resource: Spree::Permission.model_name.human) %>
<% end %>

<%= form_for [:admin, @permission] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/permissions/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:permissions) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_permission), new_object_url, class: "btn-success", icon: 'add', id: 'admin_new_permission_link' %>
<% end if can? :create, Spree::Permission %>

<% if @permissions.any? %>
  <div class="searchable-scrollable-list">
    <table class="table">
      <thead>
        <tr data-hook="admin_permissions_index_headers">
          <th><%= Spree.t(:permission_title) %></th>
          <th><%= Spree.t(:permission_priority) %></th>
          <th><%= Spree.t(:permission_visible) %></th>
          <th class="actions"></th>
        </tr>
      </thead>
      <tbody>
        <% @permissions.each do |permission|%>
          <tr id="<%= spree_dom_id permission %>" data-hook="admin_permissions_index_rows" class="search-target">
            <td><%= permission.title %></td>
            <td><%= permission.priority %></td>
            <td><%= permission.visible %></td>
            <td class="actions text-right">
              <%= link_to_edit(permission, no_text: true) if can? :edit, permission %>
              <%= link_to_delete(permission, no_text: true) if can? :destroy, permission %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="alert alert-warning">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Permission)) %>,
    <%= link_to(Spree.t(:add_one), new_object_url) if can? :create, Spree::Permission %>!
  </div>
<% end %>

app/views/spree/admin/permissions/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:permissions), admin_permissions_path %> /
  <%= Spree.t(:new_permission) %>
<% end %>

<%= form_for [:admin, @permission] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/permissions/new.js.erb
$("#new_permission").html('<%= escape_javascript(render :template => "spree/admin/permissions/new", :formats => [:html], :handlers => [:erb]) %>');
$("#new_permission_link").parent().hide();