config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :roles, except: [:show]
    resources :permissions, except: [:show]
    resources :permission_sets
    resource :default_admin_dashboard, only: :show
  end
end

app/models/spree/permission_set.rb
module Spree
  class PermissionSet < ActiveRecord::Base
    has_many :permissions_permission_sets, dependent: :destroy
    has_many :permissions, through: :permissions_permission_sets
    has_many :roles_permission_sets, dependent: :destroy
    has_many :roles, through: :roles_permission_sets

    validates :name, presence: true, uniqueness: true
    validates :permissions, length: { minimum: 1, too_short: Spree.t(:atleast_one_permission_is_required) }, on: :update
  end
end

app/controllers/spree/admin/permission_sets_controller.rb
module Spree
  module Admin
    class PermissionSetsController < ResourceController
      before_action :load_permissions, only: [:edit, :new, :create, :update]

      def index
        if params[:q]
          params[:q][:s] = params[:q][:s] || 'updated_at desc'
        else
          params[:q] = {}
          params[:q][:s] = "updated_at desc"
        end
        @search = Spree::PermissionSet.ransack(params[:q])
        @permission_sets = @search.result(distinct: true)
      end

      private def permitted_resource_params
        params.require(:permission_set).permit(:name, :description, :display_permission, permission_ids: [])
      end

      private def load_permissions
        @permissions = Spree::Permission.visible.all
      end
    end
  end
end

app/views/spree/admin/permission_sets/_form.html.erb
<div class="alert alert-info"><%= Spree.t(:permission_set_admin_permission_required) %></div>

<div data-hook="admin_permission_set_form_fields">
  <div class="inline-input-row col-xs-12">
    <%= f.field_container :name, class: ['form-group input-group input-group-md'] do %>
      <%= f.label :name, Spree.t(:permission_set_name), class: 'sr-only' %><span class="required"></span>
      <%= f.text_field :name, class: 'form-control full-width-input', placeholder: 'Name of the permission set' %>
      <%= f.error_message_on :name, class: 'help-block' %>
    <% end %>
    <%= f.field_container :description, class: ['form-group input-group input-group-md'] do %>
      <%= f.label :description, Spree.t(:permission_set_description), class: 'sr-only' %>
      <%= f.text_field :description, class: 'form-control full-width-input', placeholder: 'This permission set allows the role to...' %>
      <%= f.error_message_on :description, class: 'help-block' %>
    <% end %>
  </div>

  <%= f.field_container :display_permission, class: ['form-group'] do %>
    <%= f.label :display_permission, Spree.t(:permission_set_display_permission) %>
    <%= f.check_box :display_permission %>
    <p class="help-block"><%= Spree.t(:permission_set_display_permission_help) %></p>
    <%= f.error_message_on :display_permission %>
  <% end %>

  <%= f.field_container :permissions, class: ['form-group input-group col-xs-12'] do %>
    <%= hidden_field_tag 'permission_set[permission_ids][]', [] %>
    <%- @permission_set.permissions.to_a %>
    <div class="searchable-scrollable-list">
      <%- p_groups = @permissions.group_by { |permission|
          if permission.title.include?('can-read')
          'Read Permissions'
          elsif permission.title.include?('can-manage')
          'Manage Permissions'
          else
          'Other Permissions'
          end
      } %>
      <% ['Read Permissions', 'Manage Permissions', 'Other Permissions'].each do |title| %>
        <%= render 'spree/admin/shared/checkbox_list_pane', {
            items: p_groups[title],
            title: title,
            is_checked: lambda { |x| @permission_set.permissions.include? x },
            field: 'permission_set[permission_ids][]'
        } %>
      <% end %>
    </div>
    <%= f.error_message_on :permissions %>
  <% end %>
  <div data-hook="additional_permission_fields"></div>
</div>

app/views/spree/admin/permission_sets/_permission_pane.html.erb
<%- selected_count = items.select { |item| is_checked.call(item) }.count %>
<%- available_count = items.count %>
<div class="panel-group scrollable-list-group-item">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= title %><span class="badge pull-right count"><%= selected_count %>/<%= available_count %></span></h3>
    </div>
    <ul class="list-group">
      <% items.each do |item| %>
        <li class="<%= is_checked.call(item) ? 'list-group-item-success list-group-item search-target' : 'list-group-item search-target' %>">
          <%= label_tag do %>
            <%= check_box_tag field, item.id, is_checked.call(item), class: 'hide' %>
            <%= render item_partial, { item: item } %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/spree/admin/permission_sets/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:permission_sets), admin_permission_sets_path %> /
  <%= Spree.t(:editing_resource, resource: Spree::PermissionSet.model_name.human) %>
<% end %>

<%= form_for [:admin, @permission_set], { html: { class: 'form-inline centered-floating-buttons' } } do |f| %>
  <div class="form-fields-group">
    <%= render partial: 'form', locals: { f: f } %>
  </div>
  <div class="fixed-bottom-button-group text-center">
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </div>
<% end %>

app/views/spree/admin/permission_sets/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:permission_sets) %>
<% end %>

<% if can? :create, Spree::PermissionSet %>
  <% content_for :page_actions do %>
    <%= button_link_to Spree.t(:new_permission_set), new_object_url, class: 'btn btn-success', icon: 'add', id: 'admi_new_permission_set_link' %>
  <% end %>
<% end %>

<% if @permission_sets.present? %>
  <div class="searchable-scrollable-list">
    <table class="table">
      <thead>
        <tr data-hook="admin_permission_sets_index_headers">
          <th><%= sort_link @search, :name, Spree.t(:permission_set_name) %></th>
          <th><%= sort_link @search, :updated_at, Spree.t(:permission_set_last_updated)%></th>
          <th class="actions"></th>
        </tr>
      </thead>
      <tbody>
        <% @permission_sets.each do |permission_set| %>
          <tr id="<%= spree_dom_id permission_set %>" data-hook="admin_permissions_index_rows" class="search-target">
            <td><%= permission_set.name %></td>
            <td title="<%= permission_set.updated_at %>"><%= time_ago_in_words(permission_set.updated_at) %> ago</td>
            <td class="actions text-right">
              <%= link_to_edit(permission_set, no_text: true) if can? :edit, permission_set %>
              <%= link_to_delete(permission_set, no_text: true) if can? :destroy, permission_set %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/spree/admin/permission_sets/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:permission_sets), admin_permission_sets_path %> /
  <%= Spree.t(:new_permission_set) %>
<% end %>

<%= form_for [:admin, @permission_set], html: { class: 'form-inline centered-floating-buttons' } do |f| %>
  <div class="form-fields-group">
    <%= render partial: 'form', locals: { f: f } %>
  </div>
  <div class="fixed-bottom-button-group text-center">
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </div>
<% end %>